services:
  portifolio:
    container_name: portifolio
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - NAME=CHANGE-ME
      - USER=CHANGE-ME
      - PASSWORD=CHANGE-ME
      - HOST=CHANGE-ME
      - PORT=CHANGE-ME
    depends_on:
      - db

  db:
    image: postgres:17.5
    container_name: db
    environment:
      - POSTGRES_DB=CHANGE-ME
      - POSTGRES_USER=CHANGE-ME
      - POSTGRES_PASSWORD=CHANGE-ME
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
